behaviors:
  My Behavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      learning_rate: 3.0e-4
      tau: 0.005
      steps_per_update: 10
      save_replay_buffer: true
      init_entcoef: 0.2
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000
