behaviors:
  My Behavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 64
      buffer_size: 50000
      learning_rate: 3.0e-4
      tau: 0.005
      steps_per_update: 10
      save_replay_buffer: true
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory:
        memory_size: 128
        sequence_length: 16
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    checkpoint_interval: 50000
