behaviors:
  My Behavior:
    trainer: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 10240
      learning_rate: 3.0e-4
      num_epoch: 3
    network_settings:
      normalize: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
